-- Declarative row specs for the menu's settings sections. One row = one config
-- field with both languages inline; ui.lua's renderer walks these, and the
-- search index is built from the same labels -- add a row here and it's
-- searchable automatically. Custom widgets (profile cards, calibration,
-- replay library) stay hand-drawn in ui.lua.
--
-- Row types: group (header), slider (float), int, toggle, combo
-- (items = {{v=value, en=, ua=}}), text, key (keyboard bind), btn
-- (controller button bind). expert=true rows hide in Simple mode.

local M = {}

M.camera = {
    {group = true, en = 'Spawn', ua = 'Спавн'},
    {f = 'spawn_offset_fwd', type = 'slider', mn = 0, mx = 10, fmt = '%.1f',
     en = 'Spawn distance ahead', ua = 'Дистанція спавну попереду',
     hint_en = 'How far in front of you the drone appears.',
     hint_ua = 'Як далеко попереду тебе з\'являється дрон.'},
    {f = 'spawn_offset_up', type = 'slider', mn = 0, mx = 5, fmt = '%.1f',
     en = 'Spawn height', ua = 'Висота спавну',
     hint_en = 'How high above the ground it appears.',
     hint_ua = 'Як високо над землею він з\'являється.'},
    {group = true, en = 'FPV camera', ua = 'FPV-камера'},
    {f = 'cam_mount_fwd', type = 'slider', mn = -1, mx = 1, fmt = '%.2f', expert = true,
     en = 'Camera mount forward', ua = 'Камера: зсув вперед',
     hint_en = 'Camera position along the body: forward/backward.',
     hint_ua = 'Позиція камери по корпусу: вперед/назад.'},
    {f = 'cam_mount_up', type = 'slider', mn = -1, mx = 1, fmt = '%.2f', expert = true,
     en = 'Camera mount up', ua = 'Камера: зсув вгору',
     hint_en = 'Camera position along the body: up/down.',
     hint_ua = 'Позиція камери по корпусу: вгору/вниз.'},
    {f = 'cam_tilt_deg', type = 'slider', mn = -45, mx = 45, fmt = '%.0f',
     en = 'Camera tilt (deg)', ua = 'Нахил камери (град)',
     hint_en = 'Positive tilts the view down, like a real FPV rig. Up/Down arrows in flight.',
     hint_ua = 'Додатній нахиляє камеру вниз, як на справжньому FPV. Стрілки вгору/вниз у польоті.'},
}

M.audio = {
    {group = true, en = 'Motor sound', ua = 'Звук моторів'},
    {f = 'audio_enabled', type = 'toggle', en = 'Enabled', ua = 'Увімкнено',
     hint_en = 'Motor hum on/off.',
     hint_ua = 'Гул моторів увімк/вимк.'},
    {f = 'audio_vol_max', type = 'slider', mn = 0, mx = 3, fmt = '%.2f',
     en = 'Max volume (>1 amplifies)', ua = 'Гучність (>1 підсилює)',
     hint_en = 'Loudest the motors get. Above 1.0 amplifies the sample.',
     hint_ua = 'Максимальна гучність моторів. Понад 1.0 — підсилення семпла.'},
    {f = 'audio_max_range', type = 'slider', mn = 10, mx = 500, fmt = '%.0f',
     en = 'Audible range', ua = 'Дальність чутності',
     hint_en = 'Distance from the pilot at which the sound fades out.',
     hint_ua = 'Відстань від пілота, на якій звук затихає.'},
    {f = 'audio_pitch_min', type = 'slider', mn = 0.2, mx = 1.5, fmt = '%.2f', expert = true,
     en = 'Pitch at idle', ua = 'Тон на холостих',
     hint_en = 'Motor tone at zero throttle.',
     hint_ua = 'Тон моторів на нульовому газі.'},
    {f = 'audio_pitch_max', type = 'slider', mn = 0.5, mx = 3.0, fmt = '%.2f', expert = true,
     en = 'Pitch at full throttle', ua = 'Тон на повному газі',
     hint_en = 'Motor tone at full throttle. Wider gap = more dramatic.',
     hint_ua = 'Тон на повному газі. Більший розрив = драматичніше.'},
}

M.world = {
    {group = true, en = 'Police (singleplayer)', ua = 'Поліція (сінглплеєр)'},
    {f = 'sp_bullet_vulnerable', type = 'toggle',
     en = 'Police can shoot the drone down', ua = 'Копи можуть збити дрон',
     hint_en = 'Wanted stars come naturally from crash explosions; police then chase the drone itself.',
     hint_ua = 'Зірки набираються вибухами крашів; поліція женеться саме за дроном.'},
    {f = 'sp_drone_health', type = 'slider', mn = 1000, mx = 10000, fmt = '%.0f',
     en = 'Drone toughness', ua = 'Живучість дрона',
     hint_en = 'Damage the drone soaks before police fire downs it.',
     hint_ua = 'Скільки шкоди дрон тримає, перш ніж копи зіб\'ють.'},
    {f = 'crash_explosion_type', type = 'combo',
     en = 'Crash explosion', ua = 'Вибух при краші',
     hint_en = 'Which real GTA explosion a crash makes. Damages everything nearby.',
     hint_ua = 'Який справжній вибух GTA робить краш. Ранить все навколо.',
     items = {
        {en = 'Grenade', ua = 'Граната'}, {en = 'Molotov', ua = 'Молотов'},
        {en = 'Rocket', ua = 'Ракета'}, {en = 'Weak rocket', ua = 'Слабка ракета'},
        {en = 'Car', ua = 'Машина'}, {en = 'Quick car', ua = 'Швидка машина'},
        {en = 'Boat', ua = 'Човен'}, {en = 'Aircraft', ua = 'Літак'},
        {en = 'Mine', ua = 'Міна'}, {en = 'Object', ua = "Об'єкт"},
        {en = 'Tank shell', ua = 'Танковий снаряд'}, {en = 'Small', ua = 'Малий'},
        {en = 'RC vehicle', ua = 'RC-машинка'},
     }},
    {group = true, en = 'Streets stay alive (singleplayer)', ua = 'Живі вулиці (сінглплеєр)'},
    {f = 'sp_ped_density', type = 'slider', mn = 0, mx = 3, fmt = '%.1f',
     en = 'People density while flying', ua = 'Щільність людей у польоті',
     hint_en = 'Multiplier for pedestrians while the drone flies. 1 = normal.',
     hint_ua = 'Множник пішоходів у польоті. 1 = звичайно.'},
    {f = 'sp_car_density', type = 'slider', mn = 0, mx = 3, fmt = '%.1f',
     en = 'Traffic density while flying', ua = 'Щільність трафіку в польоті',
     hint_en = 'Multiplier for traffic while the drone flies. 1 = normal.',
     hint_ua = 'Множник трафіку в польоті. 1 = звичайно.'},
    {f = 'sp_no_despawn', type = 'toggle',
     en = 'No despawn around the drone', ua = 'Без деспавну навколо дрона',
     hint_en = 'Pins peds/cars near the drone so they don\'t vanish off-screen.',
     hint_ua = 'Пінить педів/машини біля дрона, щоб не зникали поза екраном.'},
    {f = 'sp_keep_radius', type = 'slider', mn = 50, mx = 500, fmt = '%.0f',
     en = 'No-despawn radius', ua = 'Радіус без деспавну',
     hint_en = 'How far around the drone the world is pinned alive.',
     hint_ua = 'Радіус, у якому світ навколо дрона лишається живим.'},
    {f = 'sp_population_boost', type = 'toggle', expert = true,
     en = 'Boost engine population limits', ua = 'Підняти движкові ліміти населення',
     hint_en = 'Raises engine caps on live peds/cars while flying. Some FPS cost.',
     hint_ua = 'Піднімає движкові ліміти живих педів/машин у польоті. Трохи коштує FPS.'},
    {f = 'sp_max_peds', type = 'int', expert = true,
     en = 'Max live peds', ua = 'Макс. живих педів',
     hint_en = 'Engine default is 25.',
     hint_ua = 'Движковий дефолт — 25.'},
    {f = 'sp_max_cars', type = 'int', expert = true,
     en = 'Max live cars', ua = 'Макс. живих машин',
     hint_en = 'Engine default is 30.',
     hint_ua = 'Движковий дефолт — 30.'},
    {group = true, en = 'Wind', ua = 'Вітер'},
    {f = 'wind_enabled', type = 'toggle', en = 'Wind', ua = 'Вітер',
     hint_en = 'Steady wind + gusts pushing the drone.',
     hint_ua = 'Постійний вітер + пориви, що зносять дрон.'},
    {f = 'wind_dir_deg', type = 'slider', mn = 0, mx = 360, fmt = '%.0f',
     en = 'Direction (deg)', ua = 'Напрям (град)',
     hint_en = 'Where the wind blows FROM. 0 = north.',
     hint_ua = 'Звідки дме вітер. 0 = північ.'},
    {f = 'wind_strength', type = 'slider', mn = 0, mx = 20, fmt = '%.1f',
     en = 'Strength', ua = 'Сила',
     hint_en = 'Steady push force.',
     hint_ua = 'Сила постійного зносу.'},
    {f = 'wind_turbulence', type = 'slider', mn = 0, mx = 20, fmt = '%.1f',
     en = 'Turbulence', ua = 'Турбулентність',
     hint_en = 'Random gust amplitude.',
     hint_ua = 'Амплітуда випадкових поривів.'},
    {group = true, en = 'Signal interference (visual)', ua = 'Перешкоди сигналу (візуал)'},
    {f = 'signal_clear_range', type = 'slider', mn = 0, mx = 300, fmt = '%.0f',
     en = 'Clean signal range', ua = 'Дальність чистого сигналу',
     hint_en = 'No static within this distance of the pilot.',
     hint_ua = 'Ближче за це до пілота — чиста картинка.'},
    {f = 'signal_dead_range', type = 'slider', mn = 0, mx = 2000, fmt = '%.0f',
     en = 'Signal lost range', ua = 'Дальність втрати сигналу',
     hint_en = 'Full static at this distance. Visual only, controls still work.',
     hint_ua = 'На цій відстані — суцільний шум. Тільки візуал, керування працює.'},
}

M.controller = {
    {group = true, en = 'Axes', ua = 'Осі'},
    {f = 'axis_roll', type = 'int', axis = true, en = 'Roll axis (1-8)', ua = 'Вісь крену (1-8)',
     hint_en = 'Which controller axis is roll. Watch Calibration bars to find it.',
     hint_ua = 'Яка вісь контролера — крен. Знайди по барах калібрування.'},
    {f = 'axis_pitch', type = 'int', axis = true, en = 'Pitch axis (1-8)', ua = 'Вісь тангажу (1-8)',
     hint_en = 'Which controller axis is pitch.',
     hint_ua = 'Яка вісь контролера — тангаж.'},
    {f = 'axis_throttle', type = 'int', axis = true, en = 'Throttle axis (1-8)', ua = 'Вісь газу (1-8)',
     hint_en = 'Which controller axis is throttle.',
     hint_ua = 'Яка вісь контролера — газ.'},
    {f = 'axis_yaw', type = 'int', axis = true, en = 'Yaw axis (1-8)', ua = 'Вісь рискання (1-8)',
     hint_en = 'Which controller axis is yaw.',
     hint_ua = 'Яка вісь контролера — рискання.'},
    {f = 'axis_pitch_invert', type = 'toggle', en = 'Invert pitch', ua = 'Інвертувати тангаж',
     hint_en = 'Flip if pushing forward pitches the wrong way.',
     hint_ua = 'Увімкни, якщо тангаж працює навпаки.'},
    {f = 'axis_yaw_invert', type = 'toggle', en = 'Invert yaw', ua = 'Інвертувати рискання',
     hint_en = 'Flip if yaw turns the wrong way.',
     hint_ua = 'Увімкни, якщо рискання крутить не туди.'},
    {group = true, en = 'Arming', ua = 'Армування'},
    {f = 'arm_enabled', type = 'toggle',
     en = 'Require throttle at idle to spawn', ua = 'Спавн тільки з газом на нулі',
     hint_en = 'Real-quad safety habit: no takeoff with the throttle up.',
     hint_ua = 'Звичка безпеки з реальних квадриків: не злітати з піднятим газом.'},
    {f = 'arm_throttle_max', type = 'slider', mn = 0, mx = 0.3, fmt = '%.2f', expert = true,
     en = 'Idle throttle threshold', ua = 'Поріг нульового газу',
     hint_en = 'Throttle below this counts as idle for arming.',
     hint_ua = 'Газ нижче цього вважається нулем для армування.'},
    {group = true, en = 'Buttons', ua = 'Кнопки'},
    {f = 'arm_toggle_vk', type = 'key', en = 'Arm/disarm motors (key)', ua = 'Арм/дісарм мотори (клавіша)',
     hint_en = 'Motor kill switch: disarm mid-air and the drone drops. Re-arm needs throttle at idle.',
     hint_ua = 'Вимикач моторів: дісарм у повітрі — дрон падає. Ре-арм тільки з газом на нулі.'},
    {f = 'arm_toggle_btn', type = 'btn', en = 'Arm/disarm motors (controller)', ua = 'Арм/дісарм мотори (контролер)',
     hint_en = 'Bind a transmitter switch here -- the classic FPV arm switch.',
     hint_ua = 'Забіндь сюди тумблер пульта -- класичний FPV arm-світч.'},
    {f = 'recall_vk', type = 'key', en = 'Recall drone (key)', ua = 'Повернути дрон (клавіша)',
     hint_en = 'Teleports the drone back to you. Click, then press a key.',
     hint_ua = 'Телепортує дрон до тебе. Клікни і натисни клавішу.'},
    {f = 'recall_btn', type = 'btn', en = 'Recall drone (controller)', ua = 'Повернути дрон (контролер)',
     hint_en = 'Same, on a controller button. Click again to clear.',
     hint_ua = 'Те саме кнопкою пульта. Повторний клік очищає.'},
    {f = 'flight_mode_cycle_vk', type = 'key', en = 'Cycle flight mode (key)', ua = 'Змінити режим (клавіша)',
     hint_en = 'Cycles ACRO / LEVEL / HORIZON.',
     hint_ua = 'Перемикає ACRO / LEVEL / HORIZON.'},
    {f = 'flight_mode_cycle_btn', type = 'btn', en = 'Cycle flight mode (controller)', ua = 'Змінити режим (контролер)',
     hint_en = 'Same, on a controller button.',
     hint_ua = 'Те саме кнопкою пульта.'},
    {f = 'throttle_3d_toggle_vk', type = 'key', en = '3D throttle (key)', ua = '3D-газ (клавіша)',
     hint_en = 'Toggles 3D throttle mode.',
     hint_ua = 'Перемикає режим 3D-газу.'},
    {f = 'throttle_3d_toggle_btn', type = 'btn', en = '3D throttle (controller)', ua = '3D-газ (контролер)',
     hint_en = 'Same, on a controller button.',
     hint_ua = 'Те саме кнопкою пульта.'},
    {f = 'replay_save_vk', type = 'key', en = 'Save flight recording (key)', ua = 'Зберегти запис польоту (клавіша)',
     hint_en = 'Saves the current flight buffer to disk.',
     hint_ua = 'Зберігає поточний буфер польоту на диск.'},
    {group = true, en = 'Connection', ua = "З'єднання", expert = true},
    {f = 'port', type = 'int', expert = true,
     en = 'Bridge daemon port', ua = 'Порт демона-моста',
     hint_en = 'Bridge daemon port. Restart the script after changing.',
     hint_ua = 'Порт демона-моста. Після зміни перезапусти скрипт.'},
    {f = 'failsafe_ms', type = 'int', expert = true,
     en = 'Failsafe timeout (ms)', ua = 'Таймаут failsafe (мс)',
     hint_en = 'No packets for this long = failsafe (drone falls).',
     hint_ua = 'Немає пакетів стільки мс = failsafe (дрон падає).'},
}

M.advanced = {
    {group = true, en = 'Collision & crashes', ua = 'Колізії і краші'},
    {f = 'collision_radius', type = 'slider', mn = 0.1, mx = 3.0, fmt = '%.2f', expert = true,
     en = 'Collision ray spread', ua = 'Розліт променів колізії',
     hint_en = 'Width of the collision ray bundle. Wider = safer, less agile in gaps.',
     hint_ua = 'Ширина пучка променів колізії. Ширше = надійніше, гірше в щілинах.'},
    {f = 'crash_prop_speed', type = 'slider', mn = 0, mx = 30, fmt = '%.1f',
     en = 'Crash speed threshold (into surface)', ua = 'Поріг крашу (в поверхню)',
     hint_en = 'Hitting a surface harder than this (head-on speed) destroys the drone.',
     hint_ua = 'Удар у поверхню сильніше за це (лобова швидкість) знищує дрон.'},
    {f = 'indestructible', type = 'toggle',
     en = 'Indestructible (bounce instead of crash)', ua = 'Безсмертя (відскок замість вибуху)',
     hint_en = 'Crash-grade impacts bounce off instead of exploding.',
     hint_ua = 'Смертельні удари відскакують замість вибуху.'},
    {f = 'bounce_restitution', type = 'slider', mn = 0, mx = 1, fmt = '%.2f',
     en = 'Bounce springiness', ua = 'Пружність відскоку',
     hint_en = '1 = perfectly bouncy, 0 = stops dead against the wall.',
     hint_ua = '1 = ідеально пружний, 0 = просто гаситься об стіну.'},
    {f = 'slide_friction', type = 'slider', mn = 0.2, mx = 10, fmt = '%.1f', expert = true,
     en = 'Slide friction', ua = 'Тертя ковзання',
     hint_en = 'How fast a belly slide bleeds speed. Higher = stops sooner.',
     hint_ua = 'Як швидко ковзання гасить швидкість. Більше = зупиняється раніше.'},
    {f = 'slide_stop_speed', type = 'slider', mn = 0.1, mx = 5, fmt = '%.1f', expert = true,
     en = 'Slide full-stop speed', ua = 'Швидкість повної зупинки',
     hint_en = 'Below this the slide settles into resting.',
     hint_ua = 'Нижче цього ковзання переходить у спокій.'},
    {f = 'liftoff_throttle_min', type = 'slider', mn = 0, mx = 0.5, fmt = '%.2f', expert = true,
     en = 'Liftoff throttle', ua = 'Газ для зльоту',
     hint_en = 'Throttle needed to leave the ground after landing.',
     hint_ua = 'Газ, потрібний щоб відірватися після посадки.'},
    {f = 'crash_cooldown_ms', type = 'int', expert = true,
     en = 'Crash cooldown (ms)', ua = 'Пауза після крашу (мс)',
     hint_en = 'Wait before you can spawn again after a crash.',
     hint_ua = 'Пауза перед новим спавном після крашу.'},
    {f = 'crash_view_delay_ms', type = 'int', expert = true,
     en = 'Wreck view time (ms)', ua = 'Час огляду уламків (мс)',
     hint_en = 'How long the camera watches the wreck.',
     hint_ua = 'Скільки камера дивиться на уламки.'},
    {f = 'auto_respawn_after_crash', type = 'toggle',
     en = 'Auto-respawn after crash', ua = 'Авто-респавн після крашу',
     hint_en = 'A fresh drone spawns by itself after the cooldown.',
     hint_ua = 'Новий дрон з\'являється сам після паузи.'},
    {group = true, en = 'Cheat phrases', ua = 'Чит-фрази'},
    {f = 'cheat_spawn', type = 'text', en = 'Spawn/despawn phrase', ua = 'Фраза спавну/деспавну',
     hint_en = 'Type this in-game to spawn/despawn the drone.',
     hint_ua = 'Набери це в грі, щоб заспавнити/прибрати дрон.'},
    {f = 'cheat_menu', type = 'text', en = 'Menu phrase', ua = 'Фраза меню',
     hint_en = 'Type this in-game to open this menu.',
     hint_ua = 'Набери це в грі, щоб відкрити це меню.'},
}

M.replay = {
    {group = true, en = 'Recording', ua = 'Запис'},
    {f = 'replay_ring_frames', type = 'int', expert = true,
     en = 'Buffer size (frames)', ua = 'Розмір буфера (кадрів)',
     hint_en = 'How many frames the flight buffer holds. More = longer recordings, more RAM.',
     hint_ua = 'Скільки кадрів тримає буфер. Більше = довші записи, більше RAM.'},
    {f = 'replay_max_entities', type = 'int', expert = true,
     en = 'Max entities per frame', ua = 'Макс. сутностей на кадр',
     hint_en = 'Cars/peds recorded around you per frame.',
     hint_ua = 'Скільки машин/педів пишеться навколо тебе на кадр.'},
    {f = 'replay_capture_radius', type = 'slider', mn = 50, mx = 500, fmt = '%.0f', expert = true,
     en = 'Capture radius', ua = 'Радіус захоплення',
     hint_en = 'Entities within this range get recorded.',
     hint_ua = 'Сутності в цьому радіусі потрапляють у запис.'},
}

return M
